name = "Coinductive"
version = "0.1.0"
defaultTargets = ["Coinductive", "Test", "ITree"]

[[lean_lib]]
name = "Coinductive"

[[lean_lib]]
name = "Test"
globs = ["Test.+"]

[[lean_lib]]
name = "ITree"
